rvm: 2.2.3
language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - gem install xcpretty cocoapods
  - pod install
script: xcodebuild -workspace CSSSelectorConverter.xcworkspace -scheme CSSSelectorConverter -sdk iphonesimulator test  | xcpretty -c; exit ${PIPESTATUS[0]}
