#import <ParseKit/PKSParser.h>

enum {
    CSSSELECTORPARSER_TOKEN_KIND_UNIVERSALSELECTOR = 14,
    CSSSELECTORPARSER_TOKEN_KIND_INCLUDES,
    CSSSELECTORPARSER_TOKEN_KIND_PLUS,
    CSSSELECTORPARSER_TOKEN_KIND_OPEN_BRACKET,
    CSSSELECTORPARSER_TOKEN_KIND_POUND,
    CSSSELECTORPARSER_TOKEN_KIND_COMMA,
    CSSSELECTORPARSER_TOKEN_KIND_EQUAL,
    CSSSELECTORPARSER_TOKEN_KIND_GT,
    CSSSELECTORPARSER_TOKEN_KIND_CLOSE_BRACKET,
    CSSSELECTORPARSER_TOKEN_KIND_DOT,
};

@interface CSSSelectorParser : PKSParser

@end

