#import <ParseKit/PKSParser.h>

enum {
    CSSSELECTORPARSER_TOKEN_KIND_INCLUDES = 14,
    CSSSELECTORPARSER_TOKEN_KIND_COMMA,
    CSSSELECTORPARSER_TOKEN_KIND_COLON,
    CSSSELECTORPARSER_TOKEN_KIND_TILDE,
    CSSSELECTORPARSER_TOKEN_KIND_MINUS,
    CSSSELECTORPARSER_TOKEN_KIND_NTHCONSTANT,
    CSSSELECTORPARSER_TOKEN_KIND_DOT,
    CSSSELECTORPARSER_TOKEN_KIND_ODD,
    CSSSELECTORPARSER_TOKEN_KIND_LAST,
    CSSSELECTORPARSER_TOKEN_KIND_FIRST,
    CSSSELECTORPARSER_TOKEN_KIND_ONLY,
    CSSSELECTORPARSER_TOKEN_KIND_EMPTY,
    CSSSELECTORPARSER_TOKEN_KIND_POUND,
    CSSSELECTORPARSER_TOKEN_KIND_EVEN,
    CSSSELECTORPARSER_TOKEN_KIND_GT,
    CSSSELECTORPARSER_TOKEN_KIND_EQUAL,
    CSSSELECTORPARSER_TOKEN_KIND_OPEN_BRACKET,
    CSSSELECTORPARSER_TOKEN_KIND_TYPE,
    CSSSELECTORPARSER_TOKEN_KIND_DASHMATCH,
    CSSSELECTORPARSER_TOKEN_KIND_CLOSE_BRACKET,
    CSSSELECTORPARSER_TOKEN_KIND_OPEN_PAREN,
    CSSSELECTORPARSER_TOKEN_KIND_CLOSE_PAREN,
    CSSSELECTORPARSER_TOKEN_KIND_OF,
    CSSSELECTORPARSER_TOKEN_KIND_UNIVERSALSELECTOR,
    CSSSELECTORPARSER_TOKEN_KIND_NTHCHILDCONSTANT,
    CSSSELECTORPARSER_TOKEN_KIND_PLUS,
    CSSSELECTORPARSER_TOKEN_KIND_CHILD,
};

@interface CSSSelectorParser : PKSParser

@end

